<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJyjucmo\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJyjucmo/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerJyjucmo.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerJyjucmo\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerJyjucmo\appProdProjectContainer([
    'container.build_hash' => 'Jyjucmo',
    'container.build_id' => '2aeeff1f',
    'container.build_time' => 1683514226,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJyjucmo');
